# fly.toml app configuration file generated for gigachad on 2023-07-08T16:46:51+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gigachad"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
